import Pro from '../images/pro.webp'
import Guess from '../images/guess.png'
const workData=[
    {
        imgurl:Pro,
        title:"Virtual Assistant",
        text:"ThisVirtualAssistant will help you to access and open other pages and applications from your running program with the help of your voice- Commands.",
        view:"https://github.com/chetansai123/VirtualAssistant",
    },
    {
        imgurl:Guess,
        title:"Guess The Number Game",
        text:"This is a program to guess the number generated by a computer.The number of times taken to guess will be counted.",
        view:"https://github.com/chetansai123/GuessingGame"
    }

]

export default workData