import Pro from '../images/pro.webp'
import Guess from '../images/guess.png'
import YoutubeClone from "../images/youtubeClone.png"

const workData = [
    {
        imgurl: Pro,
        title: "Virtual Assistant",
        text: "ThisVirtualAssistant will help you to access and open other pages and applications from your running program with the help of your voice- Commands.",
        view: "https://github.com/chetansai123/VirtualAssistant",
    },
    {
        imgurl: Guess,
        title: "Guess The Number Game",
        text: "This is a program to guess the number generated by a computer.The number of times taken to guess will be counted.",
        view: "https://github.com/chetansai123/GuessingGame"
    },
    {
        imgurl: YoutubeClone,
        title: "Youtube Clone",
        text: " This is a YouTube Clone Project developed using ReactJS and Material UI.",
        view: "https://youtube-clone-standard.netlify.app/"
    }

]

export default workData